# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: defensa

# HTML Language setting
#lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
#plugins:
#  # Automatically fetch Medium follower count
#  - MediumFollowersCountPlugin:
#      username: zhgchgli
#  # Automatically fetch Github repo star count
#  - GithubRepoStarsCountPlugin:
#      - ZhgChgLi/ZMarkupParser
#      - ZhgChgLi/ZReviewTender
#      - ZhgChgLi/ZMediumToMarkdown
#      - ZhgChgLi/linkyee
plugins:
  - I18n:
      supported_langs: ["en", "es", "zh"]
      translations:
        Title:
          en: "Richmond Defensa"
          es: "Richmond Defensa"
          zh: "里士满地分撒"
        Name:
          en: "@richmonddefensa"
          es: "@richmonddefensa"
          zh: "@richmonddefensa"
        Tagline:
          en: "Richmond Defensa is a community defense network dedicated to protecting and upholding our immigrant brothers, sisters, and siblings in the Richmond, VA metro area"
          es: "Richmond Defensa es una red de defensa comunitaria dedicada a proteger y apoyar a nuestros hermanos, hermanas y hermanes inmigrantes en el área metropolitana de Richmond, Virginia"
          zh: "里士满地分撒是一个社区防卫网络，致力于保护并维护我们在里士满都会区的移民家人的权益"
        Instagram:
          en: "Richmond Defensa's Instagram"
          es: "Instagram de Richmond Defensa"
          zh: "里士满地分撒的Instagram"
        Telegram:
          en: "Receive Alerts on Telegram"
          es: "Recibe Alertas en Telegram"
          zh: "在 Telegram 接收提醒"
        WhatsApp:
          en: "Receive Alerts on WhatsApp"
          es: "Recibe Alertas en WhatsApp"
          zh: "在 WhatsApp 接收提醒"
        RAADPetition:
          en: "Sign The Artists Against Deportation Statement"
          es: "Firma La Declaración De Artistas Contra La Deportación"
          zh: "签署Artists Against Apartheid声明"
        Report:
          en: "Report Suspicious Activity"
          es: "Denunciar Actividad Sospechosa"
          zh: "举报可疑活动"
        Printables:
          en: "Download Community Defense Toolkit"
          es: "Descargar Materiales De Defensa Comunitaria"
          zh: "下载社区防御工具包"
        LAJC:
          en: "Virginia Legal Support Toolkit (Legal Aid Justice Center)"
          es: "Materiales De Apoyo Legal De Virginia (Centro de Justicia de Asistencia Legal)"
          zh: "弗吉尼亚州法律支持材料（法律援助司法中心）"

# Google Analytics tracking id
#google_analytics_id:

# HTML Title
title: "Richmond Defensa"

# Avatar image path
avatar: "./images/RVADefensa.svg"

# Name section text
#name: "@richmonddefensa"

# Tagline section text
tagline: >-
    {{vars.I18n['Tagline']}}

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-bullhorn"
      text: "<span class='link-button-text-bold'>{{vars.I18n['Report']}}</span>"
      url: "https://RVADefensa.com/report"
      alt: "RVADefensa.com/report"
      title: "Report"
      target: "_blank"
  - link:
      icon: "fa-brands fa-square-whatsapp"
      text: "{{vars.I18n['WhatsApp']}}"
      url: "/whatsapp"
      alt: "Whatsapp"
      title: "Whatsapp"
      target: "_blank"
  - link:
      icon: "fa-brands fa-telegram"
      text: "{{vars.I18n['Telegram']}}"
      url: "/telegram"
      alt: "RVADefensa.com/telegram"
      title: "Telegram"
      target: "_blank"
  - link:
      icon: "fa-solid fa-scale-balanced"
      text: "{{vars.I18n['LAJC']}}"
      url: "https://www.justice4all.org/rapid-response-toolkit/"
      alt: "www.justice4all.org/rapid-response-toolkit/"
      title: "LAJC"
      target: "_blank"
  - link:
      icon: "fa-solid fa-palette"
      text: "{{vars.I18n['RAADPetition']}}"
      url: "https://RVADefensa.com/RAAD"
      alt: "RVADefensa.com/RAAD"
      title: "Artists Against Deportation Petition"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file-arrow-down"
      text: "{{vars.I18n['Printables']}}"
      url: "https://RVADefensa.com/print"
      alt: "RVADefensa.com/print"
      title: "Print"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/richmonddefensa/"
      title: "Instagram"
      alt: "Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-square-whatsapp"
      url: "/whatsapp"
      title: "WhatsApp"
      alt: "WhatsApp"
      target: "_blank"
  - social:
      icon: "fa-brands fa-telegram"
      url: "/telegram"
      title: "Telegram"
      alt: "Telegram"
      target: "_blank"

footer: >
  {{ vars.I18n['script'] }}

copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a> 🦋
